# Generated by Django 4.1.5 on 2023-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_link', models.URLField(max_length=300)),
                ('input_folder_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'my',
            },
        ),
    ]
